defaults: &defaults

  playup_api:
    competitions:
      -
        playup_id: 53
        name:      AFL
      -
        playup_id: 26
        name:      Premier League

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
